version: '3'

services:
  postgresql:
    image: ${DOCKER_IMAGE}
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
    - 5432
    environment:
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=test
    - POSTGRES_DB=test
    - "PGCONF_log_line_prefix='%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '"
    - PGCONF_log_checkpoints=on
    - PGCONF_log_connections=on
    - PGCONF_log_disconnections=on
    - PGCONF_log_lock_waits=on
    - PGCONF_log_temp_files=0
    - PGCONF_log_autovacuum_min_duration=0
    - PGCONF_log_error_verbosity=default
    - PGCONF_log_min_duration_statement=100
#    - PGCONF_log_duration=on
    - PGHBAREPLACE=true
    - PGHBA_1=local all all trust
    - PGHBA_2=host all all 127.0.0.1/32 trust
    - PGHBA_3=host all all all md5
    restart: unless-stopped

volumes:
  postgres:
