sudo: required
services:
  - docker
language: java

jobs:
  include:
    - stage: test
      script: ./gradlew check -i
    - stage: Push docker images
      if: branch = release && type != pull_request
      script: ./gradlew pushDockerImage -i

cache:
  directories:
  - "$HOME/.gradle"